package binary;

import binary.BinaryMessage;

public class BinaryMessage1_24 implements BinaryMessage {
    private int linkage;
    private int airdraught;
    private String lastport;
    private String nextport;
    private String secondport;
    private int ais_state;
    private int ata_state;
    private int bnwas_state;
    private int ecdisb_state;
    private int chart_state;
    private int sounder_state;
    private int epaid_state;
    private int steer_state;
    private int gnss_state;
    private int gyro_state;
    private int lrit_state;
    private int magcomp_state;
    private int navtex_state;
    private int arpa_state;
    private int sband_state;
    private int xband_state;
    private int hfradio_state;
    private int inmarsat_state;
    private int mfradio_state;
    private int vhfradio_state;
    private int grndlog_state;
    private int waterlog_state;
    private int thd_state;
    private int tcs_state;
    private int vdr_state;
    private int iceclass;
    private int horsepower;
    private int vhfchan;
    private String lshiptype;
    private int tonnage;
    private int lading;
    private int heavyoil;
    private int lightoil;
    private int dieseloil;
    private int totaloil;
    private int persons;
    @Override
    public void parse(Payload payload) {
        linkage = payload.getNextNbits(10).toInteger();
        airdraught = payload.getNextNbits(13).toInteger();
        lastport = payload.getNextNbits(30).toSixBitAscii();
        nextport = payload.getNextNbits(30).toSixBitAscii();
        secondport = payload.getNextNbits(30).toSixBitAscii();
        ais_state = payload.getNextNbits(2).toInteger();
        ata_state = payload.getNextNbits(2).toInteger();
        bnwas_state = payload.getNextNbits(2).toInteger();
        ecdisb_state = payload.getNextNbits(2).toInteger();
        chart_state = payload.getNextNbits(2).toInteger();
        sounder_state = payload.getNextNbits(2).toInteger();
        epaid_state = payload.getNextNbits(2).toInteger();
        steer_state = payload.getNextNbits(2).toInteger();
        gnss_state = payload.getNextNbits(2).toInteger();
        gyro_state = payload.getNextNbits(2).toInteger();
        lrit_state = payload.getNextNbits(2).toInteger();
        magcomp_state = payload.getNextNbits(2).toInteger();
        navtex_state = payload.getNextNbits(2).toInteger();
        arpa_state = payload.getNextNbits(2).toInteger();
        sband_state = payload.getNextNbits(2).toInteger();
        xband_state = payload.getNextNbits(2).toInteger();
        hfradio_state = payload.getNextNbits(2).toInteger();
        inmarsat_state = payload.getNextNbits(2).toInteger();
        mfradio_state = payload.getNextNbits(2).toInteger();
        vhfradio_state = payload.getNextNbits(2).toInteger();
        grndlog_state = payload.getNextNbits(2).toInteger();
        waterlog_state = payload.getNextNbits(2).toInteger();
        thd_state = payload.getNextNbits(2).toInteger();
        tcs_state = payload.getNextNbits(2).toInteger();
        vdr_state = payload.getNextNbits(2).toInteger();
        iceclass = payload.getNextNbits(4).toInteger();
        horsepower = payload.getNextNbits(18).toInteger();
        vhfchan = payload.getNextNbits(12).toInteger();
        lshiptype = payload.getNextNbits(42).toSixBitAscii();
        tonnage = payload.getNextNbits(18).toInteger();
        lading = payload.getNextNbits(2).toInteger();
        heavyoil = payload.getNextNbits(2).toInteger();
        lightoil = payload.getNextNbits(2).toInteger();
        dieseloil = payload.getNextNbits(2).toInteger();
        totaloil = payload.getNextNbits(14).toInteger();
        persons = payload.getNextNbits(13).toInteger();
    }
}
