package com.rinus.binary;
import com.rinus.decoder.Payload;

public class BinaryMessage1_21 implements BinaryMessage {
    private int wmo;
    private String location;
    private float lon;
    private float lat;
    private int day;
    private int hour;
    private int minute;
    private int weather;
    private int vislimit;
    private float visibility;
    private int humidity;
    private int wspeed;
    private int wdir;
    private int pressure;
    private int pressuretend;
    private float airtemp;
    private float watertemp;
    private int waveperiod;
    private float waveheight;
    private int wavedir;
    private float swellheight;
    private int swelldir;
    private int swellperiod;

    private int surftemp;
    private int month;
    private int course;
    private float speed;
    private int heading;
    private float pdelta;
    private int ptend;
    private int twinddir;
    private int twindspeed;
    private int rwinddir;
    private float rwindspeed;
    private float mgustspeed;
    private int mgustdir;
    private int pweather1;
    private int pweather2;
    private int totalcloud;
    private int lowclouda;
    private int lowcloudt;
    private int midcloudt;
    private int highcloudt;
    private float cloudbase;
    private int wwperiod;
    private int wwheight;
    private int swelldir1;
    private int swperiod1;
    private float swheight1;
    private int swelldir2;
    private int swperiod2;
    private float swheight2;
    private int icedeposit;
    private int icerate;
    private int icecause;
    private int seaice;
    private int icetype;
    private int icestate;
    private int icedevel;
    private int icebearing;
    @Override
    public void parse(Payload payload) {
        wmo = payload.getNextNbits(1).toInteger();
        if(wmo == 0)
        {
            location = payload.getNextNbits(120).toSixBitAscii();
            lon = payload.getNextNbits(25).toSignedInt() * 0.0001f / 60;
            lat = payload.getNextNbits(24).toSignedInt() * 0.0001f / 60;
            day = payload.getNextNbits(5).toInteger();
            hour = payload.getNextNbits(5).toInteger();
            minute = payload.getNextNbits(6).toInteger();
            weather = payload.getNextNbits(4).toInteger();
            vislimit = payload.getNextNbits(1).toInteger();
            visibility = payload.getNextNbits(7).toInteger();
            humidity = payload.getNextNbits(7).toInteger();
            wspeed = payload.getNextNbits(7).toInteger();
            wdir = payload.getNextNbits(9).toInteger();
            pressure = payload.getNextNbits(9).toInteger();
            pressuretend = payload.getNextNbits(4).toInteger();
            airtemp = payload.getNextNbits(11).toSignedInt();
            watertemp = payload.getNextNbits(10).toSignedInt();
            waveperiod = payload.getNextNbits(6).toInteger();
            waveheight = payload.getNextNbits(8).toInteger();
            wavedir = payload.getNextNbits(9).toInteger();
            swellheight = payload.getNextNbits(8).toInteger();
            swelldir = payload.getNextNbits(9).toInteger();
            swellperiod = payload.getNextNbits(6).toInteger();
        }else
        {
            lon = payload.getNextNbits(16).toSignedInt() / 100f - 189;
            lat = payload.getNextNbits(15).toSignedInt() / 100f - 90;
            month = payload.getNextNbits(4).toInteger();
            day = payload.getNextNbits(6).toInteger();
            hour = payload.getNextNbits(5).toInteger();
            minute = payload.getNextNbits(3).toInteger();
            course = payload.getNextNbits(7).toInteger();
            speed = payload.getNextNbits(5).toInteger();
            heading = payload.getNextNbits(7).toInteger();
            pressure = payload.getNextNbits(11).toInteger();
            pdelta = payload.getNextNbits(10).toInteger();
            ptend = payload.getNextNbits(4).toInteger();
            twinddir = payload.getNextNbits(7).toInteger();
            twindspeed = payload.getNextNbits(8).toInteger();
            rwinddir = payload.getNextNbits(7).toInteger();
            rwindspeed = payload.getNextNbits(8).toInteger();
            mgustspeed = payload.getNextNbits(8).toInteger();
            mgustdir = payload.getNextNbits(7).toInteger();
            airtemp = payload.getNextNbits(10).toInteger();
            humidity = payload.getNextNbits(7).toInteger();
            surftemp = payload.getNextNbits(9).toInteger();
            visibility = payload.getNextNbits(6).toInteger();
            weather = payload.getNextNbits(9).toInteger();
            pweather1 = payload.getNextNbits(5).toInteger();
            pweather2 = payload.getNextNbits(5).toInteger();
            totalcloud = payload.getNextNbits(4).toInteger();
            lowclouda = payload.getNextNbits(4).toInteger();
            lowcloudt = payload.getNextNbits(6).toInteger();
            midcloudt = payload.getNextNbits(6).toInteger();
            highcloudt = payload.getNextNbits(6).toInteger();
            cloudbase = payload.getNextNbits(7).toInteger();
            wwperiod = payload.getNextNbits(5).toInteger();
            wwheight = payload.getNextNbits(6).toInteger();
            swelldir1 = payload.getNextNbits(6).toInteger();
            swperiod1 = payload.getNextNbits(5).toInteger();
            swheight1 = payload.getNextNbits(6).toInteger();
            swelldir2 = payload.getNextNbits(6).toInteger();
            swperiod2 = payload.getNextNbits(5).toInteger();
            swheight2 = payload.getNextNbits(6).toInteger();
            icedeposit = payload.getNextNbits(7).toInteger();
            icerate = payload.getNextNbits(3).toInteger();
            icecause = payload.getNextNbits(3).toInteger();
            seaice = payload.getNextNbits(5).toInteger();
            icetype = payload.getNextNbits(4).toInteger();
            icestate = payload.getNextNbits(5).toInteger();
            icedevel = payload.getNextNbits(5).toInteger();
        }
    }
}
