public class Types {
    public static final String[] navigationStatus = {"En marcha con motor", "Al ancla", "No bajo mando", "Maniobrabilidad restringida",
                "Restringido por su calado", "Amarrado", "Encallado", "Dedicado a la pesca", "Navegando en camino", "Reservado para futuras enmiendas del estado de navegación para HSC",
                "Reservado para futuras enmiendas del estado de navegación para WIG", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "AIS-SART está activo",
                "No definido (por defecto)"};
    public static final String[] possitionAccuracy = {"Correción del GNSS no aumentada con precisión > 10 m", "Correción de la calidad del DGPS con precisión < 10 ms"};
    public static final String[] epfdTypes = {"No definido", "GPS", "GLONASS", "GPS/GLONASS", "LORAN-C", "Chayka", "Sistema integrado de navegación", "Surveyed", "Galileo"};
    public static final String[] maneuverIndicators = {"No disponible (por defecto)", "Ninguna maniobra especial", "Manobra especial"};
    public static final String[] shipTypes = {"No disponible (Por defecto)", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso",
                "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Reservado para futuro uso", "Ekranoplano", "Ekranoplano, Hazardous Categoría A", "Ekranoplano, Hazardous Categoría B",
                "Ekranoplano, Hazardous Categoría C", "Ekranoplano, Hazardous Categoría D", "Ekranoplano, reservado para futuro uso", "Ekranoplano, reservado para futuro uso", "Ekranoplano, reservado para futuro uso", "Ekranoplano, reservado para futuro uso", "Ekranoplano, reservado para futuro uso",
                "De pesca", "Embarcación de remolque", "Embarcación de remolque: su longitud excede los 200m o su ancho los 25m", "Embarcación con draga", "Embarcación de buceo", "Militar", "Embarcación de vela", "Yate", "Reservado", "Reservado", "Embarcación de alta velocidad", "Embarcación de alta velocidad, peligrosa Categoría A", "Embarcación de alta velocidad, peligrosa Categoría B", "Embarcación de alta velocidad, peligrosa Categoría C",
                "Embarcación de alta velocidad, peligrosa Categoría D", "Embarcación de alta velocidad, reservada para futuro uso", "Embarcación de alta velocidad, reservada para futuro uso", "Embarcación de alta velocidad, reservada para futuro uso", "Embarcación de alta velocidad, reservada para futuro uso", "Embarcación de alta velocidad, sin información adicional", "Barco piloto", "De búsqueda y rescate", "Remolcador", "Barco nodriza",
                "Barco de limpieza", "Barco de la ley", "Spare - local vessel", "Spare - local vessel", "De transporte médico", "Nave no combatiente", "De pasajeros", "De pasajeros, hazardous Categoría A", "De pasajeros, hazardous Categoría B", "De pasajeros, hazardous Categoría C", "De pasajeros, hazardous Categoría D", "De pasajeros, reservado para futuro uso", "De pasajeros, reservado para futuro uso", "De pasajeros, reservado para futuro uso", "De pasajeros, reservado para futuro uso",
                "De pasajeros, sin información adicional", "De carga", "De carga, hazardous Categoría A", "De carga, hazardous Categoría B", "De carga, hazardous Categoría C", "De carga, hazardous Categoría D", "De carga, reservado para futuro uso", "De carga, reservado para futuro uso", "De carga, reservado para futuro uso", "De carga, reservado para futuro uso", "De carga, sin información adicional", "Buque cisterna", "Buque cisterna, hazardous Categoría A", "Buque cisterna, hazardous Categoría B",
                "Buque cisterna, hazardous Categoría C", "Buque cisterna, hazardous Categoría D", "Buque cisterna, reservado para futuro uso", "Buque cisterna, reservado para futuro uso", "Buque cisterna, reservado para futuro uso", "Buque cisterna, reservado para futuro uso", "Buque cisterna, sin información adicional", "Otro tipo", "Otro tipo, hazardous Categoría A", "Otro tipo, hazardous Categoría B", "Otro tipo, hazardous Categoría C",
                "Otro tipo, hazardous Categoría D", "Otro tipo, reservado para futuro uso", "Otro tipo, reservado para futuro uso", "Otro tipo, reservado para futuro uso", "Otro tipo, reservado para futuro uso", "Otro tipo, sin información adicional"};
    public static final String [] transmitModes = {"TxA/TxB, RxA, RxB (por defecto)", "TxA, RxA/RxB", "TxB, RxA/RxB", "Reservado para futuro uso"};
    public static final String [] navaidTypes = {"Por defecto, tipo de Aid no especificado", "Punto de referencia", "Transpondedor de radar (RACON)", "Plataforma costa afuera", "Reservado para futuro uso", "Light, without sectors", "Light, with sectors", "Leading Light Front", "Leading Light Rear", "Faro Norte", "Faro Este", "Faro sur", "Faro oeste", "Faro porthand", "Faro starboard hand", "Faro preferred channel porthand",
    "Faro preffered channel starboard hand", "Faro de peligro aislado", "Faro de aguas seguras", "Faro de marca especial", "Marca cardinal norte", "Marca cardinal este", "Marca cardinal sur", "Marca cardinal oeste", "Marca port hand", "Marca starboard hand", "Preferred Channel Port hand", "Preferred Channel Starboard hand", "Peligro aislado", "Aguas seguras", "Marca especial", "Light Vessel"};
}
